### ISSUE TITLE
Margin Calculated weirdly

### ISSUE THREAD

**Issue by ramsaylanier** [typeplate/starter-kit#40]
As mentioned in #23, libsass interpolates some things weirdly. The proposed correction was to update _typeplate_function.scss as follow:

```
// $Context Calculator
// -------------------------------------//
// target / context = result
//
// @example             p { font-size: context-calc(24, 16, px); }

@function typl8-context-calc($scale, $base, $value) {
  @return #{$scale/$base}#{$value}; // chaining two interpolations
}


// $Measure-Margin
// -------------------------------------//
// divide 1 unit of measure by given font-size & return relative value
@function typl8-measure-margin($scale, $measure, $value) {
  $pixelValue: $measure/$scale;
  $remValue: $pixelValue * $typl8-font-base;

  @if $value == rem {
    @return #{$pixelValue}#{$value};
  } @else if $value == em {
    @return #{$remValue/$scale}#{$value};
  } @else {
    @return #{$remValue}#{$value};
  }
}
```

However, this was causing my Heading margins to be calculated backwards, meaning the H1 bottom margin was smaller than, say, and H3 as seen here.
![screen shot 2015-02-16 at 1 03 24 pm](https://cloud.githubusercontent.com/assets/2359852/6216929/7b9c6640-b5dc-11e4-8d54-33095839a4e1.png)

I found that by switching the $pixelValue calculation from $measure/$scale to $scale/$measure fixes the issue, I think?

![screen shot 2015-02-16 at 1 07 14 pm](https://cloud.githubusercontent.com/assets/2359852/6216953/c54b98f6-b5dc-11e4-89a0-43ace3351ffd.png)

Is this....correct?

**Comment by justindietert** [comment]
The CSS version of Typeplate still uses the measure/scale method for calculating heading margins. I have found that this method produces a proper vertical rhythm for headings (in my opinion).

I just started using the SASS version, and the fix incorporated here has broken the vertical rhythm of my headings. There is now far too much space below a heading the larger that heading gets.

Perhaps the calculation should be switched back to $measure/$scale, as originally designed?
