### ISSUE TITLE
What would be considered attribution?

### ISSUE THREAD

**Issue by neil-119** [typeplate/starter-kit#45]
I noticed that this library is licensed under CC 3.0. What would be the correct way to attribute? Does including the following in the source code considered an attribution, or do the credits need to appear on the page?

/*!
Typeplate:
URL ........... http://typeplate.com
Authors ....... Dennis Gaebel (@gryghostvisuals) & Zachary Kain (@zakkain)
License ....... Creative Commmons Attribution 3.0
License URL ... https://github.com/typeplate/starter-kit/blob/master/license.txt
*/

**Comment by grayghostvisuals** [comment]
You can either leave those comments in or make a note somewhere like @Melindrea does it on her site [http://mariehogebrandt.se/colophon](http://mariehogebrandt.se/colophon) or you could even link to the [license](https://github.com/typeplate/starter-kit/blob/master/license.txt) someplace. If you are still unsure or need further guidance you can email me at grayghost @ grayghostvisuals dot com.
