### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by maruilian11** [typeplate/starter-kit#47]
would you please consider adding package.json so that we can add your lib on https://cdnjs.com/.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5010

**Comment by grayghostvisuals** [comment]
It is actually in the development branch [https://github.com/typeplate/starter-kit/blob/development/package.json](https://github.com/typeplate/starter-kit/blob/development/package.json) so it stays out of the distributed files, but I can consider this in the coming days. Appreciate the offer :)

**Comment by maruilian11** [comment]
@grayghostvisuals thank you!

**Comment by josephdburdick** [comment]
This would be awesome, :+1: .

**Comment by grayghostvisuals** [comment]
@maruilian11 This is now ready to be included for CDNJS. Let me know when it is added :)

**Comment by maruilian11** [comment]
thank you very much!
our people already added :smiley: 
https://cdnjs.com/libraries/typeplate-starter-kit

**Comment by grayghostvisuals** [comment]
wow! so fast! thanks so much. :beers:
