### ISSUE TITLE
Does change of scale ratio requires changes to headings margins

### ISSUE THREAD

**Issue by Madebym** [typeplate/starter-kit#49]
Let's say that I implement a different scale ratio than the one you are using now, does that require changes to headings margins and line heights? Or I can leave the default ones?

Please note that I am using the CSS version of Typeplate, so I am not sure if that makes any difference, because I am not dealing with any variables or scss settings.

**Comment by grayghostvisuals** [comment]
Yeah, you will need to recalculate everything. In the future the idea is to create a builder making this easier on everyone whether it's Sass or CSS.

**Comment by Madebym** [comment]
That would be really nice thing to have !
