### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by grayghostvisuals** [typeplate/starter-kit#52]
WE need the README really updated.
- [ ] Add explanation about developing on the development branch instead of master.

**Comment by KasperAndersson** [comment]
- [ ] Add documentation for npm installation

**Comment by grayghostvisuals** [comment]
@KasperAndersson Could u list that out for me here since I don't use NPM much?

**Comment by KasperAndersson** [comment]
@grayghostvisuals Hi, made a PR on this issue - https://github.com/typeplate/starter-kit/pull/60
