### ISSUE TITLE
Add as npm package

### ISSUE THREAD

**Issue by ronilaukkarinen** [typeplate/starter-kit#56]
Could not find this with [npm](https://www.npmjs.com/search?q=typeplate). Many have moved from bower to npm-only, so have I. It would be great to be able to use this directly from upstream. Would you be so kind to add typeplate as npm package. Appreciated!

**Comment by grayghostvisuals** [comment]
Related : [https://docs.npmjs.com/getting-started/creating-node-modules](https://docs.npmjs.com/getting-started/creating-node-modules)

**Comment by KasperAndersson** [comment]
@dennisgaebel What's status on this?

**Comment by grayghostvisuals** [comment]
Nothing in motion yet at this time, but still intend to at some point.

**Comment by KasperAndersson** [comment]
@grayghostvisuals Nice, just started a big project - and want to use it. For now I've added it manually, but would love to have it a npm.

**Comment by grayghostvisuals** [comment]
That's good to hear thanks. Been extremely busy on other things but it's on the list. If you run into any problems using the kit let me know and i'm happy to help. 🍺

**Comment by KasperAndersson** [comment]
@grayghostvisuals Weekend project, to get this on npm? :)

**Comment by grayghostvisuals** [comment]
@KasperAndersson I'll do my best

**Comment by KasperAndersson** [comment]
@grayghostvisuals Thanks, starting a big international project for a client, and would love to use the libary. I found that copying the source files into a project is risky working in bigger teams..

**Comment by grayghostvisuals** [comment]
Give me tonight to get this in.

**Comment by KasperAndersson** [comment]
@grayghostvisuals Works like a charm! Thank you, i'll let you know when we go live with the production 👍

**Comment by grayghostvisuals** [comment]
Grrrreat! Appreciate it.
