### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by TheBeardedLlama** [typeplate/starter-kit#65]
Hey, I inherited a project that uses this plugin and I'm wondering if it's still maintained?
It looks like it isn't, but I'd rather make sure.
Cheers!

**Comment by grayghostvisuals** [comment]
Closing this issue, but if you have any questions please go ahead and file a new ticket pertaining to your topic and I'll be happy to help.

**Comment by TheBeardedLlama** [comment]
Apologies @grayghostvisuals, I missed your original reply

I wasn't looking for help, just making sure that I refresh any deprecated packages (there were quite a few in that project)

There is one thing actually, npm audit is reporting vulnerabilities. Is there any chance of updating the dependencies to fix them? I'd be happy to submit a PR if you like

**Comment by grayghostvisuals** [comment]
@TheBeardedLlama Feel free to send a PR. It would be much appreciated 🍻
