### ISSUE TITLE
Refresh dependencies

### ISSUE THREAD

**Issue by TheBeardedLlama** [typeplate/starter-kit#66]
Adding an issue to track updating the dependencies as discussed in #65

**Comment by TheBeardedLlama** [comment]
PS. I messed up the commit... I will nuke and resubmit... apologies

**Comment by TheBeardedLlama** [comment]
I've created the PR @grayghostvisuals 

Haven't committed any changes for the versioning, so that's missing, but the rest should be there

**Comment by grayghostvisuals** [comment]
@TheBeardedLlama Ty very much for your efforts and time. Appreciate your patience as it will have to be pulled in, inspected, tested then released on master branch from our end.

**Comment by grayghostvisuals** [comment]
All set. Thanks again @TheBeardedLlama

**Comment by TheBeardedLlama** [comment]
My pleasure @grayghostvisuals

**Comment by TheBeardedLlama** [comment]
when shall I expect to see it released?

**Comment by grayghostvisuals** [comment]
@TheBeardedLlama Master branch is updated now. All set.

**Comment by TheBeardedLlama** [comment]
Hey @grayghostvisuals have you released it to npm? I can't see it there

It'd be grand if you could do that please :)

**Comment by dennisgaebel** [comment]
@TheBeardedLlama Had some issues with logging into the npm registry, but I was finally able to fix that, and publish the package. Just had to update the version number in the package.json. LMK if that works for you 🍻

**Comment by TheBeardedLlama** [comment]
cheers mate!

should do, but I will let you know if there are any issues :)

many thanks :)
